version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    commit-message:
      prefix: ":package::mechanic: NPM deps: "
    labels:
      - dependabot
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
